### ISSUE TITLE
App切换中文语言bug

### ISSUE THREAD

**Issue by h94666** [bitwarden/ios#1061] opened 2024-10-20 05:34 UTC
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

![IMG_0243]（https://github.com/user-attachments/assets/97e65efa-990d-405d-b4ae-739bb2420396)

目前这个App语言问题的版本号是2024.9.2（1106）

### Expected Result

可以给App语言改为中文

### Actual Result

改了中文但是没有反应

### Build Version

2024.9.2 （1106）

### Environment Details

iPhone 15Promax

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-10-21 01:50
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/ios/issues/747

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-10-21 01:50 UTC
Labels: bug
