### ISSUE TITLE
Invalid language setting

### ISSUE THREAD

**Issue by jiaobaba1027** [bitwarden/ios#895] opened 2024-09-05 04:15 UTC
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

Traditional Chinese and Simplified Chinese settings are invalid

https://github.com/user-attachments/assets/446ad55b-261b-4724-b438-d3fa65cbebab

### Expected Result

Please help me fix the problem of invalid Simplified Chinese and Traditional Chinese. Thanks

### Actual Result

Please help me fix the problem of invalid Simplified Chinese and Traditional Chinese. Thanks

### Build Version

IOS 2024.8.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by xingyue52077** [comment] 2024-09-05 05:12
me too！

**Comment by sammbw** [comment] 2024-09-05 05:49
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by jiaobaba1027** [comment] 2024-09-05 06:03
In addition, face recognition is also buggy, and it does not work when calling face recognition to automatically fill in passwords.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bitwarden/ios"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月5日(星期四) 中午1:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bitwarden/ios] Invalid language setting (Issue #895)





 
Hi there,
 
Thank you for your report!
 
I was able to reproduce this issue, and I have flagged this to our engineering team.
 
If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.
 
Thanks once again!

**Comment by YangH9** [comment] 2024-09-08 13:32
I have also encountered this problem
IPhone 13 Pro Max version iOS 17.6.1
IPhone 13 version iOS 17.6

**Comment by gzxiexl** [comment] 2024-09-09 01:23
metoo

**Comment by jiaobaba1027** [comment] 2024-09-10 09:07
Hello, has it been repaired?

**Comment by jiaobaba1027** [comment] 2024-09-18 18:27
iphone13 pro MAX， IOS 18.0 ，The language setting is still invalid

**Comment by jiaobaba1027** [comment] 2024-09-18 18:28
> Hi there,
> 
> Thank you for your report!
> 
> I was able to reproduce this issue, and I have flagged this to our engineering team.
> 
> If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.
> 
> Thanks once again!

iphone13 pro MAX， IOS 18.0 ，The language setting is still invalid

**Comment by sammbw** [comment] 2024-09-19 02:52
@bwbug thanks for the heads up, this does appear to be a duplicate of: https://github.com/bitwarden/ios/issues/747

I'm going to close this issue - please follow the other issue to track the progress.

**Closed by sammbw** 2024-09-19 02:52 UTC
Labels: bug
