### ISSUE TITLE
Clone option doesn't exist for organization items

### ISSUE THREAD

**Issue by trparky** [bitwarden/ios#1030] opened 2024-10-10 17:36 UTC
### Bitwarden Beta

- [x] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open Bitwarden app.
2. Click on Vaults at the bottom of the screen.
3. Find an item that's not in your organization, tap on it. Tap the three dots in the upper right corner. Note how there's an option to clone the item.
4. Go back to your Vault.
5. Find an item in your organization vault, tap on it. Tap the three dots in the upper right corner. Note how there's **no** option to clone the item.

### Expected Result

See the Steps to Reproduce section.

### Actual Result

See the Steps to Reproduce section.

### Build Version

2024.9.2 (1106)

### Environment Details

iPhone 15 Pro, iOS version 18.0.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment] 2024-10-11 12:43
Hi there,

You can clone any item that you have ownership of if you want to create a duplicate of the item. Cloning items owned by an organization can only be done from the web app in the Admin Console or from Vaults view by Owners, Admins, and Users with Can manage access to the collection in which the item is kept. Please see the documentation here: https://bitwarden.com/help/managing-items/#clone

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Closed by jtodddd** 2024-10-11 12:43 UTC
Labels: bug

**Comment by trparky** [comment] 2024-10-12 00:11
But why can't items be cloned in anything but the web app? That sounds kind of silly.
