### ISSUE TITLE
Edit crashes if two consequtive dash characters (--) are in Notes

### ISSUE THREAD

**Issue by yz778** [bitwarden/ios#745] opened 2024-07-17 23:43 UTC
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Using Bitwarden Chrome Extension, create a new entry

2. Type 2 dashes (--) in the Notes and Save, other fields don't matter
![image](https://github.com/user-attachments/assets/a3b440cd-fe39-4285-a69c-5af031427504)

3. Launch the iOS Bitwarden application

4. Search for the new entry from Step 2

5. Click Edit, and it will crash immediately

### Expected Result

iOS Bitwarden shouldn't crash

### Actual Result

iOS Bitwarden crashes

### Build Version

24.6.0 (7846)

### Environment Details

iOS 17.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-07-29 02:38
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/mobile/issues/3146

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Comment by Greenderella** [comment] 2024-08-08 08:18
Reopening, as the issue is also present on the native app.

**Comment by Greenderella** [comment] 2024-08-15 11:07
Hi @yz778 

This issue is no longer reproducible on the iOS beta native app, please make sure you update the app to the latest available version.

**Closed by Greenderella** 2024-08-15 11:07 UTC
Labels: bug
