### ISSUE TITLE
Fehler / Error after password login 

### ISSUE THREAD

**Issue by julesptzk** [bitwarden/ios#930] opened 2024-09-15 10:38 UTC
### Bitwarden Beta

- [x] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

2. Tap on '...'
3. Scroll down to '...'
4. Tap on '...'
![IMG_0021](https://github.com/user-attachments/assets/b63e23e2-0223-4431-86af-81bd3ce1b969)

### Expected Result

..

### Actual Result

iOS 18.0 (22A5326f)

App says after Password Login: Fehler / Error

### Screenshots or Videos

![IMG_0021](https://github.com/user-attachments/assets/181af860-08f0-4eb5-b55d-2390c9f5f7b1)

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-09-16 13:54
Hello @julesptzk,

Thank you for reporting this. I recommend that you consider using a fresh new installation; Please uninstall Bitwarden off your iOS device, turn your device off (long press) and back on, install Bitwarden anew from the Apple App Store, and give that another try. I say this because I am unable to reproduce this behaviour. Please note that this may also be related to iOS 18; It generally is recommended to stick to Stable Channel releases for an optimal experience.

If you continue to experience this in iOS 18 once it's released as a stable operating system, please feel free to get in [touch with us](https://bitwarden.com/help/) so we'd have a look at this together.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Closed by SergeantConfused** 2024-09-16 13:54 UTC
Labels: bug

**Comment by chrissi5120** [comment] 2024-10-02 07:05
Same error here, tried your debugging steps without success. Running iOS 18.0 and Bitwarden 2024.9.2

**Comment by chrissi5120** [comment] 2024-10-02 14:05
@julesptzk can you please reopen the issue?
