### ISSUE TITLE
The automatic detection and setting of i18n has failed.

### ISSUE THREAD

**Issue by LSR-0417** [bitwarden/ios#1021] opened 2024-10-08 18:12 UTC
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. iPhone OS language: Traditional Chinese (繁體中文)
2. Lunch Bitwarden iOS app, still English UI
3. Bitwarden iOS app Settings Language, set Traditional Chinese (中文(台灣))
4. Bitwarden iOS app, UI language still English
5. Close Bitwarden iOS app and re lunch app
6. Bitwarden iOS app, UI language still English

### Expected Result

Bitwarden iOS app, UI language auto change to Traditional Chinese, same with iOS default Language.

### Actual Result

Bitwarden iOS app, UI language still English.

### Build Version

2024.9.2 (1106)

### Environment Details

- Device: iPhone 15 Pro
- OS version: 18.0
- OS language: Traditional Chinese (中文(台灣))

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by luc-bw** [comment] 2024-10-08 21:49
Hi @LSR-0417 

Thank you for your report, it seems like it is a duplicate of https://github.com/bitwarden/ios/issues/747

This issue will now be closed.

Thanks!

**Closed** 2024-10-08 21:49 UTC
Labels: bug
