### ISSUE TITLE
After selecting the Chinese language in the iOS client, the language does not switch to Chinese.

### ISSUE THREAD

**Issue by fightroad** [bitwarden/ios#950] opened 2024-09-19 02:41 UTC
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

After selecting the Chinese language in the iOS client, the language does not switch to Chinese.

### Expected Result

After selecting the Chinese language in the iOS client, the language does not switch to Chinese.

### Actual Result

can switch to Chinese.

### Build Version

2024.9.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-09-19 03:00
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/ios/issues/747

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-09-19 03:00 UTC
Labels: bug
